CREATE TABLE crime_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    crime_type TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    region TEXT NOT NULL,
    city TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_description TEXT,
    incident_date TIMESTAMPTZ NOT NULL,
    severity TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending',
    'investigating',
    'resolved',
    'closed')),
    evidence_urls TEXT[],
    is_anonymous BOOLEAN DEFAULT false,
    assigned_officer UUID REFERENCES profiles(id),
    resolution_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);